@baseUrl = http://localhost:3000

### Login ADMIN
# @name loginAdmin
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "admin@helpdesk.com",
  "password": "Admin@123"
}

### Login CLIENT
# @name loginClient
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "pedro.client@helpdesk.com",
  "password": "Client@123"
}

### Criar ticket como CLIENT (pra ter um id)
# @name createTicketClient
POST {{baseUrl}}/tickets
Authorization: Bearer {{loginClient.response.body.token}}
Content-Type: application/json

{
  "title": "Ticket para assign",
  "description": "Teste do dia 6"
}

### PATCH assign como ADMIN (200) - atribui pra um AGENT
PATCH {{baseUrl}}/tickets/{{createTicketClient.response.body.id}}/assign
Authorization: Bearer {{loginAdmin.response.body.token}}
Content-Type: application/json

{
  "assignedToId": "u-101"
}

### PATCH assign sem assignedToId (400)
PATCH {{baseUrl}}/tickets/{{createTicketClient.response.body.id}}/assign
Authorization: Bearer {{loginAdmin.response.body.token}}
Content-Type: application/json

{
}

### PATCH assign como CLIENT (403)
PATCH {{baseUrl}}/tickets/{{createTicketClient.response.body.id}}/assign
Authorization: Bearer {{loginClient.response.body.token}}
Content-Type: application/json

{
  "assignedToId": "u-101"
}

### PATCH assign ticket inexistente (404 para admin/agent)
PATCH {{baseUrl}}/tickets/does-not-exist/assign
Authorization: Bearer {{loginAdmin.response.body.token}}
Content-Type: application/json

{
  "assignedToId": "u-101"
}

### PATCH assign assignedToId inexistente (404)
PATCH {{baseUrl}}/tickets/{{createTicketClient.response.body.id}}/assign
Authorization: Bearer {{loginAdmin.response.body.token}}
Content-Type: application/json

{
  "assignedToId": "u-999"
}
