@baseUrl = http://localhost:3000

### Login ADMIN
# @name loginAdmin
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "admin@helpdesk.com",
  "password": "Admin@123"
}

### Login CLIENT
# @name loginClient
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "pedro.client@helpdesk.com",
  "password": "Client@123"
}

### Criar ticket como ADMIN
POST {{baseUrl}}/tickets
Authorization: Bearer {{loginAdmin.response.body.token}}
Content-Type: application/json

{
  "title": "Ticket admin",
  "description": "Criado pelo admin"
}

### Criar ticket como CLIENT
POST {{baseUrl}}/tickets
Authorization: Bearer {{loginClient.response.body.token}}
Content-Type: application/json

{
  "title": "Ticket client",
  "description": "Criado pelo client"
}

### Listar tickets como ADMIN (deve ver todos)
GET {{baseUrl}}/tickets
Authorization: Bearer {{loginAdmin.response.body.token}}

### Listar tickets como CLIENT (deve ver só os próprios)
GET {{baseUrl}}/tickets
Authorization: Bearer {{loginClient.response.body.token}}

### Listar tickets sem token (deve 401)
GET {{baseUrl}}/tickets
