@baseUrl = http://localhost:3000

### POST /users - Criar novo usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Isaac Newton",
  "email": "i_newton@email.com",
  "password": "Client@123"
}

### POST /users - Criar usuário já existente
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Pedro Álvares Cabral",
  "email": "i_newton@email.com",
  "password": "Client@123"
}

### POST /users - Criar usuário sem dados obrigatórios
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Pedro Álvares Cabral",
  "email": "pedro.client@helpdesk.com"
}
